FROM golang:1.25-alpine AS caddy-builder
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
RUN xcaddy build v2.10.2 \
    --with github.com/caddy-dns/cloudflare \ 
    ##--with github.com/caddy-dns/powerdns \
    --with github.com/ss098/certmagic-s3 \
    --with github.com/pberkel/caddy-storage-redis \
    --with github.com/zhangjiayin/caddy-mysql-storage \
    --with github.com/yroc92/postgres-storage \
    --with github.com/mholt/caddy-ratelimit \
    --with github.com/kirsch33/realip \
    --with github.com/greenpau/caddy-security \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --output /usr/local/bin/caddy

# Image starts here
FROM alpine:3
LABEL maintainer="Gamal Abdul Nasser <gamalanpro@gmail.com>"

RUN apk add -U --no-cache ca-certificates

EXPOSE 80 443 2019
ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data

WORKDIR /
COPY --from=caddy-builder /usr/local/bin/caddy /bin/caddy

ENTRYPOINT ["/bin/caddy"]

CMD ["docker-proxy"]